In [5]:
from google.colab import files
uploaded = files.upload()

Saving Bangla_Sports_Sentiment_Analysis_Dataset.xlsx to Bangla_Sports_Sentiment_Analysis_Dataset.xlsx

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from io import StringIO

# Get uploaded file name
file_name = list(uploaded.keys())[0]

# Read Excel
df = pd.read_excel(file_name)

print("🔍 Original Dataset Preview")
display(df.head())

print("\n📌 Dataset Info:")
df.info()

print("\n📊 Missing Values:")
display(df.isnull().sum())

print("\n📈 Statistical Summary:")
display(df.describe())

🔍 Original Dataset Preview

,Comment,Category,Cleaned_Text
0,মনে হয় পাড়া-মহল্লার খেলা দেখছি।,Positive,মন হয় পাড়া মহল্ল খেলা দেখ
1,বাংলাদেশের ফুটবল না খেলে কুত কুত খেললেই পারে,Positive,বাংলাদেশ ফুটবল খালা কুত কুত খেললে
2,বাংলাদেশের দামরা ছেলে গুলো কি খেলছে,Positive,বাংলাদেশ দাম ছালা খেল
3,সুফল সুমন রেজা মতিন মিয়া এগুলা বল রাখতেই পারেনা,Positive,সুফল সুমন রেজা মতিন মিয়া এগুলা বল রাখতে পারেনা
4,"খারাপ লাগে তখন যখন,,,একজন বল বাস করে গোলের দিক...",Positive,খারাপ লাগ যখন একজন বল বাস গোল ছোর প্লেয় সামন য...

📌 Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82611 entries, 0 to 82610
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Comment       82606 non-null  object
 1   Category      82611 non-null  object
 2   Cleaned_Text  82270 non-null  object
dtypes: object(3)
memory usage: 1.9+ MB

📊 Missing Values:

Comment           5
Category          0
Cleaned_Text    341
dtype: int64

📈 Statistical Summary:

       Comment   Category Cleaned_Text
count     82606     82611        82270
unique    47947         2        45270
top     অসাধারণ  Negative      অসাধারণ
freq        251     41355          343

In [7]:
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

if len(numeric_cols) > 0:
    col = numeric_cols[0]  # first numeric column

    plt.figure()
    sns.histplot(df[col], kde=True)
    plt.title(f"Distribution of {col} (Original Data)")
    plt.show()

In [8]:
csv_file = "converted_file.csv"

# Convert
df.to_csv(csv_file, index=False, encoding='utf-8')

print("✅ Conversion Done!")

✅ Conversion Done!

In [9]:
df_csv = pd.read_csv(csv_file)

print("🔍 CSV Dataset Preview")
display(df_csv.head())

print("\n📌 CSV Info:")
df_csv.info()

print("\n📊 Missing Values (CSV):")
display(df_csv.isnull().sum())

print("\n📈 Statistical Summary (CSV):")
display(df_csv.describe())

🔍 CSV Dataset Preview

,Comment,Category,Cleaned_Text
0,মনে হয় পাড়া-মহল্লার খেলা দেখছি।,Positive,মন হয় পাড়া মহল্ল খেলা দেখ
1,বাংলাদেশের ফুটবল না খেলে কুত কুত খেললেই পারে,Positive,বাংলাদেশ ফুটবল খালা কুত কুত খেললে
2,বাংলাদেশের দামরা ছেলে গুলো কি খেলছে,Positive,বাংলাদেশ দাম ছালা খেল
3,সুফল সুমন রেজা মতিন মিয়া এগুলা বল রাখতেই পারেনা,Positive,সুফল সুমন রেজা মতিন মিয়া এগুলা বল রাখতে পারেনা
4,"খারাপ লাগে তখন যখন,,,একজন বল বাস করে গোলের দিক...",Positive,খারাপ লাগ যখন একজন বল বাস গোল ছোর প্লেয় সামন য...

📌 CSV Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82611 entries, 0 to 82610
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Comment       82606 non-null  object
 1   Category      82611 non-null  object
 2   Cleaned_Text  82270 non-null  object
dtypes: object(3)
memory usage: 1.9+ MB

📊 Missing Values (CSV):

Comment           5
Category          0
Cleaned_Text    341
dtype: int64

📈 Statistical Summary (CSV):

       Comment   Category Cleaned_Text
count     82606     82611        82270
unique    47947         2        45270
top     অসাধারণ  Negative      অসাধারণ
freq        251     41355          343

In [11]:
numeric_cols_csv = df_csv.select_dtypes(include=['int64', 'float64']).columns

if len(numeric_cols_csv) > 0:
    col2 = numeric_cols_csv[0]

    plt.figure()
    sns.histplot(df_csv[col2], kde=True)
    plt.title(f"Distribution of {col2} (CSV Data)")
    plt.show()

In [12]:
files.download(csv_file)

In [14]:
# Correlation Heatmap
correlation_matrix = df.corr(numeric_only=True)

if not correlation_matrix.empty:
    plt.figure()
    sns.heatmap(correlation_matrix, annot=True)
    plt.title("Correlation Heatmap (Original Data)")
    plt.show()
else:
    print("No numeric columns found in the DataFrame to generate a correlation heatmap.")

No numeric columns found in the DataFrame to generate a correlation heatmap.